defaultEntryPoints:
  - websecure

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

certificatesResolvers:
  letsencrypt:
    acme:
      email: rustamov.shaxriyor371@gmail.com
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

providers:
  file:
    filename: /config.yml
    watch: true

  docker:
    exposedByDefault: false

accessLog: { }

api:
  dashboard: true
